name: CD to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_USERNAME_PASSWORD }}
        key: ${{ secrets.SSH_SECRET_KEY }}
        script: |
          cd /var/www/nextjs/AArt
          git pull origin main
          npm install
          rm -rf .next
          npm run build
          pm2 restart all
